# logging_config.yaml

version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: "/app/logs/risk_assessment_tool.log"

loggers:
  src:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

  src.utils:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler]
